# Generated by Django 3.0.3 on 2020-06-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertables', '0003_auto_20200624_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='0098-1231-1233',
            name='Age of user',
        ),
        migrations.AddField(
            model_name='0098-1231-1233',
            name='Ageofuser',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
