# Generated by Django 3.0.3 on 2020-06-24 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usertables', '0004_auto_20200624_1845'),
    ]

    operations = [
        migrations.DeleteModel(
            name='0098-1231-1233',
        ),
    ]
