# Generated by Django 3.0.3 on 2020-06-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertables', '0008_auto_20200624_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usertables009812311235',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ageofuser', models.IntegerField(blank=True, db_column='Ageofuser', null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=100, null=True)),
            ],
            options={
                'db_table': 'usertables_0098-1231-1235',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='0098-1231-1236',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('firstname', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('lastname', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='0098-1231-1235',
        ),
        migrations.DeleteModel(
            name='Usertables009812311234',
        ),
    ]
