# Generated by Django 3.0.3 on 2020-06-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertables', '0009_auto_20200624_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usertables009812311236',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('lastname', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'usertables_0098-1231-1236',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Usertables009812311235',
        ),
    ]
