# Generated by Django 3.0.3 on 2020-06-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertables', '0010_auto_20200624_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='0098-1231-1237',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('firstname', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('lastname', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='0098-1231-1236',
        ),
    ]
